# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(396, 318)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(12, 12, 12, 12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.b = QtWidgets.QLabel(self.centralwidget)
        self.b.setObjectName("b")
        self.verticalLayout_4.addWidget(self.b, 0, QtCore.Qt.AlignHCenter)
        self.power = QtWidgets.QCheckBox(self.centralwidget)
        self.power.setEnabled(False)
        self.power.setObjectName("power")
        self.verticalLayout_4.addWidget(self.power, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setCheckable(True)
        self.btn.setAutoExclusive(False)
        self.btn.setFlat(True)
        self.btn.setObjectName("btn")
        self.horizontalLayout_7.addWidget(self.btn)
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setCheckable(True)
        self.btn2.setAutoExclusive(False)
        self.btn2.setFlat(True)
        self.btn2.setObjectName("btn2")
        self.horizontalLayout_7.addWidget(self.btn2)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.colorbtn = QtWidgets.QPushButton(self.centralwidget)
        self.colorbtn.setObjectName("colorbtn")
        self.horizontalLayout_8.addWidget(self.colorbtn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.strobeOffBtn = QtWidgets.QPushButton(self.centralwidget)
        self.strobeOffBtn.setCheckable(True)
        self.strobeOffBtn.setChecked(True)
        self.strobeOffBtn.setAutoExclusive(True)
        self.strobeOffBtn.setObjectName("strobeOffBtn")
        self.horizontalLayout.addWidget(self.strobeOffBtn)
        self.strobeOnBtn = QtWidgets.QPushButton(self.centralwidget)
        self.strobeOnBtn.setCheckable(True)
        self.strobeOnBtn.setAutoExclusive(True)
        self.strobeOnBtn.setObjectName("strobeOnBtn")
        self.horizontalLayout.addWidget(self.strobeOnBtn)
        self.strobePulseBtn = QtWidgets.QPushButton(self.centralwidget)
        self.strobePulseBtn.setCheckable(True)
        self.strobePulseBtn.setAutoExclusive(True)
        self.strobePulseBtn.setObjectName("strobePulseBtn")
        self.horizontalLayout.addWidget(self.strobePulseBtn)
        self.strobeRandomBtn = QtWidgets.QPushButton(self.centralwidget)
        self.strobeRandomBtn.setCheckable(True)
        self.strobeRandomBtn.setAutoExclusive(True)
        self.strobeRandomBtn.setObjectName("strobeRandomBtn")
        self.horizontalLayout.addWidget(self.strobeRandomBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.strobeslider = QtWidgets.QSlider(self.centralwidget)
        self.strobeslider.setOrientation(QtCore.Qt.Horizontal)
        self.strobeslider.setObjectName("strobeslider")
        self.horizontalLayout_3.addWidget(self.strobeslider)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ADJ Fog Fury Jett"))
        self.b.setText(_translate("MainWindow", "Ansluter..."))
        self.power.setText(_translate("MainWindow", "Ström på"))
        self.btn.setText(_translate("MainWindow", "KÖR FÄRG"))
        self.btn2.setText(_translate("MainWindow", "KÖR ELD"))
        self.colorbtn.setText(_translate("MainWindow", "Välj färg"))
        self.label.setText(_translate("MainWindow", "Stroboskopkontroll"))
        self.strobeOffBtn.setText(_translate("MainWindow", "Av"))
        self.strobeOnBtn.setText(_translate("MainWindow", "Strobo"))
        self.strobePulseBtn.setText(_translate("MainWindow", "Puls"))
        self.strobeRandomBtn.setText(_translate("MainWindow", "Slumpmässig"))
        self.label_2.setText(_translate("MainWindow", "Hastighet"))

